name: chat_app_flutter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  # Add HTTP package to connect to backend
  http: ^1.2.0  # You can check for latest version on pub.dev if needed
  socket_io_client: ^2.0.3+1  # Cupertino Icons for iOS-styled icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linter package
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
